lang:
  input:
    vocab_size: 2048
    seq_len: 32
  output:
    vocab_size: 64
    seq_len: 32
dataset:
  train: ./starwars/datasets/ep4/train.pt
  val: ./starwars/datasets/ep4/val.pt
model:
  d_model: 256
  nhead: 4
  num_encoder_layers: 3
  num_decoder_layers: 3
  dim_feedforward: 2048
  temperature: 0.1
train:
  path: ./starwars/models/ep4/test.pt
  lr: 0.0001
  weight_decay: 0.0001
  dropout: 0.1
  discrete: False
  batch_size: 256
  epochs: 250
  clip_grad_norm: 1.0
