lang:
  input:
    vocab_size: 512
    seq_len: 64
  output:
    vocab_size: 512
    seq_len: 64
dataset:
  train: ./starwars/datasets/complete/train.pt
  val: ./starwars/datasets/complete/val.pt
model:
  save_path: ./starwars/models/test.pt
  d_model: 128
  nhead: 4
  num_encoder_layers: 3
  num_decoder_layers: 3
  dim_feedforward: 512
train:
  lr: 0.001
  weight_decay: 0.0001
  dropout: 0.1
  discrete: True
  batch_size: 256
  epochs: 150
  clip_grad_norm: 1.0
  temperature: 1.0
predict:
  tokenizer: ./starwars/datasets/complete/tokenizer.model
  temperature: 1.0
